name: borsvy
services:
  - name: frontend
    working_directory: frontend
    build:
      command: npm install && npm run build
    run:
      command: npm run preview
    ports:
      - port: 3000
        protocol: http
    env:
      - name: NODE_ENV
        value: production
      - name: VITE_API_URL
        value: ${API_URL}

  - name: backend
    dockerfile: backend/Dockerfile
    ports:
      - port: 8080
        protocol: http
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: production
      - name: SPRING_DATASOURCE_URL
        value: ${POSTGRESQL_URL}
      - name: SPRING_DATASOURCE_USERNAME
        value: ${POSTGRESQL_USERNAME}
      - name: SPRING_DATASOURCE_PASSWORD
        value: ${POSTGRESQL_PASSWORD}
      - name: JWT_SECRET
        value: ${JWT_SECRET} 